---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    istio-injection: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 4h0m0s
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  releaseName: external-secrets
  targetNamespace: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: ">=0.0.0-0"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
  values:
    serviceAccount:
      annotations: {}
    metrics:
      service:
        enabled: true
    installCRDs: true
    webhook:
      create: false
    certController:
      create: false
  interval: 0h4m4s
  install:
    remediation:
      retries: 4
