apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux.yaml

patches:
- target:
    kind: HelmRelease
    name: flux-sync
  patch: |-
    - op: add
      path: /spec/values/gitRepository/spec/url
      value: ssh://git@github.com:22/apexitpl/demo.git
    - op: add
      path: /spec/values/gitRepository/spec/ref/branch
      value: demo/pge
