---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels: {}
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: istio
spec:
  interval: 480m
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
spec:
  releaseName: istio-base
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      version: "=1.16.2"
  interval: 0h4m0s
  install:
    remediation:
      retries: 4
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  releaseName: istiod
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      version: "=1.16.2"
  values: {}
  interval: 0h4m0s
  install:
    remediation:
      retries: 4
